---
title: "About me"
bibliography: aboutreferences.bib
about:
  template: solana
  links:
  - icon: linkedin
    text: LinkedIn
    href: https://www.linkedin.com/in/le-dinh-351bba2a1/
  - icon: envelope
    text: Email
    href: mailto:lpdinh@colgate.edu
--- 

## Education

I'm a student double-majoring in Educational Studies and Psychological Science at Colgate University. My anticipated graduation date is May 2027. 

## Technical skills

* **Languages:** R
* **Tools:** Positron, Quarto, Git/GitHub, LaTeX

## Declaration of AI Use

In creating this website, AI was used as a replacement of search tools (e.g., Google), identifying errors (e.g., Where is the error in this code chunk/logic? My website is not updated even though my repository is---where can the problem be?), trouble-shooting errors (e.g., How can I debug this?), clarifying or providing simpler explanations of conceptual problems (e.g., Why are the bars in the PDF "stacked" on each other in the CDF? In plain language, why do we use effect size in power analysis to identify sample size?), checking clarity and grammar of writing, and criticizing my output [@cipolli2026].